DATAS SEGMENT
    ;???????????¦Ä???  
DATAS ENDS

STACK SEGMENT STACK
		STA		DB 	500 DUP(?)
		NUM 	EQU 	LENGTH STA
STACK ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACK
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV AX,STACKS
    MOV SS,AX
    MOV SP,NUM
       ;????????????¦Ä???
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START

